FROM golang:latest

EXPOSE 80

RUN mkdir -p /home/go/app

WORKDIR /home/go/app
ENV BRANCH = "master"

COPY . .
RUN go env -w GOPROXY="https://goproxy.cn" && \ 
    GO111MODULE=on go get \
    github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest \
    github.com/ramya-rao-a/go-outline@latest \
    github.com/cweill/gotests/gotests@latest \
    github.com/fatih/gomodifytags@latest \
    github.com/josharian/impl@latest \
    github.com/haya14busa/goplay/cmd/goplay@latest \
    github.com/go-delve/delve/cmd/dlv@latest \
    honnef.co/go/tools/cmd/staticcheck@latest \
    golang.org/x/tools/gopls@latest && \
    go get 

CMD ["sh", "-c", "git fetch && git checkout $BRANCH -f && git pull --ff-only && go get && bash"]